let length1="count me length";
// length1=length1.indexOf('m')
// console.log(length1)
// length1=length1.lastIndexOf("t")
// console.log(length1)
// length1=length1.includes("c",5)
// console.log(length1)
// length1=length1.slice(0,7)
// console.log(length1)
// console.log("here start substring")
// length1=length1.substring(0,7)
// console.log(length1)
// length1=length1.substr()
// console.log(length1)
// console.log(length1.replace("count","s"))
// const result=length1.split()
// console.log(result)
let result=length1.valueOf()
console.log(result)