console.log(document.body.firstChild)
console.log(document.body.lastChild)
console.log(document.body.childNodes)
console.log(document.body.hasChildNodes)
console.info(document.body.childNodes[0])
console.info(document.body.childNodes.)